version: "3"
services:
  worker:
    container_name: ai-test
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PROJECT_DIR}:/code
    ports:
      - "8888:8888"
      - "8889:8889"
